CREATE TABLE IF NOT EXISTS money_transactions (
    id INTEGER UNIQUE PRIMARY KEY AUTOINCREMENT NOT NULL,
    user_id TEXT NOT NULL,
    balance INTEGER NOT NULL,
    added_at INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS command_usage (
    command_name TEXT UNIQUE NOT NULL,
    used INT NOT NULL DEFAULT 0
);